name: local-radio-display
services:

  display:
    build: ./
    profiles:
      - display
    environment:
      - PROGRAM_ENVIRONMENT
      - RADIO_MIDDLEWARE_HOST
    volumes:
      - ./out:/app/out
