name: local-radio-display
services:

  display:
    build: ./
    profiles:
      - display
    environment:
      - PROGRAM_ENVIRONMENT
      - RADIO_MIDDLEWARE_HOST
    network_mode: host
    devices:
      - /dev/spidev0.0
      - /dev/spidev0.1
      - /dev/gpiochip0
      - /dev/gpiochip0:/dev/gpiochip4
