[project]
name = "display"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.7"
dependencies = [
	"pillow==12.3.0",
	"numpy==2.5.0",
	"spidev==3.8; sys_platform=='linux'",
	"gpiozero==2.0.1; sys_platform=='linux'",
	"python-socketio[client]==5.17.0",
]
