# Use Node base image
FROM node:22-alpine

# Install sound library
RUN apk add --no-cache ffmpeg
    
# Set the work directory
WORKDIR /usr/src/radio-middleware

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./server/package*.json ./

# Install dependencies
RUN npm ci

# Copy files
COPY ./server ./

# Run the app
CMD [ "node", "index.js" ]